# -*- coding: utf-8 -*-
"""MODEL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sUSF3Ad55Te6EHW4b_QukMsV_yv7FoKH
"""

import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/AADEESH27/Sentimental_Analyser/main/twitter-suicidal_data.csv')

df.head()

df['intention'].value_counts()

!pip install spacy==2.2.3
!python -m spacy download en_core_web_sm
!pip install beautifulsoup4==4.9.1
!pip install textblob==0.15.3

!pip install git+https://github.com/laxmimerit/preprocess_kgptalkie.git --upgrade --force-reinstall

import preprocess_kgptalkie as ps

import re

def get_clean(x):
    x = str(x).lower().replace('\\', '').replace('_', ' ')
    x = ps.cont_exp(x)
    x = ps.remove_emails(x)
    x = ps.remove_urls(x)
    x = ps.remove_html_tags(x)
    x = ps.remove_rt(x)
    x = ps.remove_accented_chars(x)
    x = ps.remove_special_chars(x)
    x = re.sub("(.)\\1{2,}", "\\1", x)
    return x

df['tweet'] = df['tweet'].apply(lambda x: get_clean(x))

df.head()

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report

tfidf = TfidfVectorizer(max_features = 20000, ngram_range = (1,3), analyzer = 'char')

X = tfidf.fit_transform(df['tweet'])
y = df['intention']

X.shape

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

clf = LinearSVC()
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

x = ''
x = get_clean(x)
vec = tfidf.transform([x])
clf.predict(vec)

